version: "3.8"

services:
  mariadb:
    image: mariadb:latest
    container_name: spring-security-jwt
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: spring-security-jwt
      MYSQL_USER: user
      MYSQL_PASSWORD: 123
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data: